package com.legend.parser.ast;

/**
 * @author Legend
 * @data by on 20-11-8.
 * @description 语法节点类型
 */
public enum ASTNodeType {

    PROGRAM,
    IMPORT_DECLARATION,

    STATEMENT,
    PAR_EXPRESSION,
    BLOCK,
    BLOCK_STATEMENT,
    BLOCK_STATEMENTS,
    FOR_CONTROL,
    FOR_INIT,
    BINARY_EXP,
    UNARY_EXP,

    TERMINAL_NODE,
    IDENTIFIER,
    INTEGER_LITERAL,
    FLOAT_LITERAL,
    CHAR_LITERAL,
    STRING_LITERAL,
    BOOL_LITERAL,
    NULL_LITERAL,

    FUNCTION_CALL_EXP,
    ARRAY_CALL_EXPR,
    DOT_EXPR,
    EXP_LIST,
    TYPE_TYPE,
    TYPE_LIST,
    TYPE_TYPE_OR_VOID,
    CLASS_OR_INTERFACE_TYPE,
    PRIMITIVE_TYPE,
    FUNCTION_TYPE,
    VARIABLE_DECLARATION,
    VARIABLE_DECLARATORS,
    VARIABLE_INITIALIZER,
    ARRAY_INITIALIZER,

    CLASS_DECLARATION,
    CLASS_BODY,
    MEMBER_DECLARATION,
    FUNCTION_DECLARATION,
    FORMAL_PARAMETER,
    FORMAL_LIST,
}
